services:
  - type: web
    name: cftt-family-support
    env: node
    plan: free
    buildCommand: npm install && node scripts/migrate.js && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cftt-family-db
          property: connectionString
      - fromGroup: cftt-family-app-env

databases:
  - name: cftt-family-db
    plan: free
    databaseName: cftt_family
    user: cftt_admin

envVarGroups:
  - name: cftt-family-app-env
    envVars:
      - key: SENDGRID_API_KEY
        sync: false